In [50]:
from   sklearn.ensemble        import RandomForestRegressor
from   sklearn.model_selection import GridSearchCV
from   sklearn.model_selection import cross_val_score
from   sklearn                 import metrics
from   sklearn                 import tree
import pandas                  as     pd
import numpy                   as     np
import seaborn                 as     sns
import matplotlib.pyplot       as     plt
import warnings
warnings.filterwarnings("ignore")

In [51]:
olympics_all = pd.read_csv(r'C:\Users\USER\Desktop\DS_python\CP4\CP4\OlympicsData\olympics_all.csv')

In [52]:
X=olympics_all.drop(['NOC', 'country','Gold','Silver','Bronze', 'Medals','GDP_Per_Capita'],axis=1)
y=olympics_all[['Year','Gold','Silver','Bronze', 'Medals']]
print(X.shape)
print(y.shape)

(544, 10)
(544, 5)

In [53]:
#Splitting data 

X_trn = X[X['Year']<2016]
X_tst = X[X['Year'] == 2016]

y_trn = y[y['Year'] < 2016]
y_tst =  y[y['Year'] == 2016]

X_train = X_trn.drop(['Year'],axis=1)
X_test  = X_tst.drop(['Year'],axis=1)
print(X_train.shape)
print(X_test.shape)

y_train = y_trn
y_test =  y_tst
print(y_train.shape)
print(y_test.shape)

(460, 9)
(84, 9)
(460, 5)
(84, 5)

In [54]:
# Create linear regression objects
rf_gold   = RandomForestRegressor(random_state=0)
rf_silver = RandomForestRegressor(random_state=0)
rf_bronze = RandomForestRegressor(random_state=0)

# Train the models using the training sets
rf_gold.  fit(  X_train, y_train['Gold'])
rf_silver.fit(X_train, y_train['Silver'])
rf_bronze.fit(X_train, y_train['Bronze'])

RandomForestRegressor(random_state=0)

In [55]:
#Testing the model

y_pred_Gold   = rf_gold.predict(X_test)
y_pred_Gold   = y_pred_Gold.astype('int64')
y_pred_Gold   = y_pred_Gold.clip(min=0)

y_pred_Silver   = rf_silver.predict(X_test)
y_pred_Silver   = y_pred_Silver.astype('int64')
y_pred_Silver   = y_pred_Silver.clip(min=0)


y_pred_Bronze   = rf_bronze.predict(X_test)
y_pred_Bronze   = y_pred_Bronze.astype('int64')
y_pred_Bronze   = y_pred_Bronze.clip(min=0)

In [60]:
#Applying k-fold cross_validation

accuracy_gold = cross_val_score(estimator=rf_gold,X=X_train,y=y_train['Gold'],cv=4)
accuracy_silver = cross_val_score(estimator=rf_silver,X=X_train,y=y_train['Silver'],cv=4)
accuracy_bronze = cross_val_score(estimator=rf_bronze,X=X_train,y=y_train['Bronze'],cv=4)

print("Gold Accuracy:", accuracy_gold)
print("Silver Accuracy:",accuracy_silver)
print("Bronze Accuracy:",accuracy_bronze)

print()
print("Gold Accuracy  :", (accuracy_gold.mean()*100).round(3), ' and Std Dev:',accuracy_gold.std().round(2))
print("Silver Accuracy:", (accuracy_silver.mean()*100).round(3), ' and Std Dev:',accuracy_silver.std().round(2))
print("Bronze Accuracy:", (accuracy_bronze.mean()*100).round(3), ' and Std Dev:',accuracy_bronze.std().round(2))
print()

Gold Accuracy: [0.87597371 0.88850843 0.88379433 0.93066988]
Silver Accuracy: [0.85974927 0.91276461 0.88095513 0.9142835 ]
Bronze Accuracy: [0.9088082  0.89567258 0.92470967 0.93859257]

Gold Accuracy  : 89.474  and Std Dev: 0.02
Silver Accuracy: 89.194  and Std Dev: 0.02
Bronze Accuracy: 91.695  and Std Dev: 0.02

In [58]:
param={'max_depth': [1, 2, 3, 4],
       'n_estimators': [100, 150, 200, 250, 300]}
grid = GridSearchCV(estimator=rf_gold,param_grid=param,cv=3)
grid.fit(X_train,y_train['Gold'])
best_accuracy  = grid.best_score_
best_parameter = grid.best_params_
print("Best Accuracy(Gold):",best_accuracy)
print("Best Parameters(Gold):",best_parameter)
print("Best Estimator(Gold):", grid.best_estimator_)
print()

param={'max_depth': [1, 2, 3, 4],
    'n_estimators': [100, 150, 200, 250, 300]}
grid = GridSearchCV(estimator=rf_silver,param_grid=param,cv=3)
grid.fit(X_train,y_train['Silver'])
best_accuracy  = grid.best_score_
best_parameter = grid.best_params_
print("Best Accuracy(Silver):",best_accuracy)
print("Best Parameters(Silver):",best_parameter)
print("Best Estimator(Silver):", grid.best_estimator_)

Best Accuracy(Gold): 0.9061952885356678
Best Parameters(Gold): {'max_depth': 3, 'n_estimators': 100}
Best Estimator(Gold): RandomForestRegressor(max_depth=3, random_state=0)

Best Accuracy(Silver): 0.8989832441883289
Best Parameters(Silver): {'max_depth': 4, 'n_estimators': 250}
Best Estimator(Silver): RandomForestRegressor(max_depth=4, n_estimators=250, random_state=0)

In [48]:
# param={'max_depth': [1, 2, 3, 4],
#                          'n_estimators': [100, 150, 200, 250, 300]}
# grid = GridSearchCV(estimator=rf_gold,param_grid=param,cv=3)
# grid.fit(X_train,y_train['Gold'])
# best_accuracy  = grid.best_score_
# best_parameter = grid.best_params_
# print("Best Accuracy for Bronze:",best_accuracy)
# print("Best Parameters for Bronze:",best_parameter)
# print("Best Estimator(Bronze):", grid.best_estimator_)

# param={'max_depth': [1, 2, 3, 4],
#                          'n_estimators': [100, 150, 200, 250, 300]}
# grid = GridSearchCV(estimator=rf_silver,param_grid=param,cv=3)
# grid.fit(X_train,y_train['Silver'])
# best_accuracy  = grid.best_score_
# best_parameter = grid.best_params_
# print("Best Accuracy for Bronze:",best_accuracy)
# print("Best Parameters for Bronze:",best_parameter)
# print("Best Estimator(Bronze):", grid.best_estimator_)


param={'max_depth': [1, 2, 3, 4 ],
                         'n_estimators': [100, 150, 200, 250, 300]}
grid = GridSearchCV(estimator=rf_bronze,param_grid=param,cv=3)
grid.fit(X_train,y_train['Bronze'])
best_accuracy  = grid.best_score_
best_parameter = grid.best_params_
print("Best Accuracy for Bronze:",best_accuracy)
print("Best Parameters(Bronze):",best_parameter)
print("Best Estimator(Bronze):", grid.best_estimator_)

Best Accuracy for Bronze: 0.918026658216104
Best Parameters for Bronze: {'max_depth': 4, 'n_estimators': 150}
Best Estimator(Bronze): RandomForestRegressor(max_depth=4, n_estimators=150, random_state=0)

In [ ]:
data = pd.read_csv(r'C:\Users\USER\Desktop\DS_python\CP4\CP4\OlympicsData\07_tokyo2020.csv')
data

In [9]:
#Prediction
data = pd.read_csv(r'C:\Users\USER\Desktop\DS_python\CP4\CP4\OlympicsData\07_tokyo2020.csv')

tokyo = data[['Population','GDP','Home_Field','Athletes','Athletes_w','Sports','Sports_w','Events','Events_w']]

PGold   = rf_gold.predict(tokyo)
PGold   = PGold.astype('int64')
PGold   = PGold.clip(min=0)
                                      
PSilver  = rf_silver.predict(tokyo)
PSilver  = PSilver.astype('int64')
PSilver  = PSilver.clip(min=0)
                                    
PBronze  = rf_bronze.predict(tokyo)
PBronze  = PSilver.astype('int64')
PBronze  = PSilver.clip(min=0)

In [13]:
print("R2(Gold)    = ", metrics.r2_score(y_test['Gold'],y_pred_Gold))
print("MSE(Gold)   = ", metrics.mean_squared_error(y_test['Gold'],y_pred_Gold))
print("MAE(Gold)   = ", metrics.mean_absolute_error(y_test['Gold'],y_pred_Gold))
print()
print("R2(Silver)  = ", metrics.r2_score(y_test['Silver'],y_pred_Silver))
print("MSE(Silver) = ", metrics.mean_squared_error(y_test['Silver'],y_pred_Silver))
print("MAE(Silver) = ", metrics.mean_absolute_error(y_test['Silver'],y_pred_Silver))
print()
print("R2(Bronze)  = ", metrics.r2_score(y_test['Bronze'],y_pred_Bronze))
print("MSE(Bronze) = ", metrics.mean_squared_error(y_test['Bronze'],y_pred_Bronze))
print("MAE(Bronze) = ", metrics.mean_absolute_error(y_test['Bronze'],y_pred_Bronze))

R2(Gold)    =  0.9225721823548007
MSE(Gold)   =  3.7142857142857144
MAE(Gold)   =  1.2142857142857142

R2(Silver)  =  0.9040012327289537
MSE(Silver) =  3.1785714285714284
MAE(Silver) =  1.2261904761904763

R2(Bronze)  =  0.8539715318238809
MSE(Bronze) =  5.892857142857143
MAE(Bronze) =  1.5119047619047619

In [14]:
# Evaluate the model's training score and test score
print("RF training score(Gold) = {:.2f}".format(rf_gold.score(X_train, y_train['Gold'])))
print("RF test score(Gold)     = {:.2f}".format(rf_gold.score(X_test, y_test['Gold'])))
print()

print("RF training score(Silver) = {:.2f}".format(rf_gold.score(X_train, y_train['Silver'])))
print("RF test score(Silver)     = {:.2f}".format(rf_gold.score(X_test, y_test['Silver'])))
print()

print("RF training score(Bronze) = {:.2f}".format(rf_gold.score(X_train, y_train['Bronze'])))
print("RF test score(Bronze)     = {:.2f}".format(rf_gold.score(X_test, y_test['Bronze'])))

RF training score(Gold) = 0.98
RF test score(Gold)     = 0.93

RF training score(Silver) = 0.81
RF test score(Silver)     = 0.85

RF training score(Bronze) = 0.77
RF test score(Bronze)     = 0.87

In [10]:
#tokyo = pd.read_csv(r"C:\Users\USER\Desktop\DS_python\CP4\CP4\07_tokyo2020.csv")

#select only wanted columns
tokyo2020_prediction = data[['NOC','country']]


tokyo2020_prediction['PGold']   = PGold.T
tokyo2020_prediction['PSilver'] = PSilver.T
tokyo2020_prediction['PBronze'] = PBronze.T

tokyo2020_prediction['Total']  =  tokyo2020_prediction['PGold'] + tokyo2020_prediction['PSilver'] + tokyo2020_prediction['PBronze']
tokyo2020_predicted = tokyo2020_prediction.sort_values(by = 'Total', ascending = False)

tokyo2020_predicted.index = np.arange(1, len(tokyo2020_predicted)+1)
tokyo2020_predicted.head(20)

    NOC      country  PGold  PSilver  PBronze  Total
1   USA          USA     40       35       35    110
2   CHN        China     35       25       25     85
3   RUS       Russia     24       20       20     64
4   GBR           UK     19       17       17     53
5   GER      Germany     11       13       13     37
6   FRA       France     10       13       13     36
7   AUS    Australia     10       12       12     34
8   JPN        Japan     12        9        9     30
9   KOR  South Korea      9        8        8     25
10  ITA        Italy      8        8        8     24
11  ESP        Spain      3        7        7     17
12  CAN       Canada      3        7        7     17
13  BRA       Brazil      3        6        6     15
14  NED  Netherlands      5        5        5     15
15  CUB         Cuba      5        4        4     13
16  UKR      Ukraine      5        4        4     13
17  HUN      Hungary      3        4        4     11
18  JAM      Jamaica      3        4        4     11
19  KEN        Kenya      4        3        3     10
20  BLR      Belarus      2        4        4     10

In [61]:
tokyo2020_predicted[tokyo2020_predicted['country'] =='Singapore']

    NOC    country  PGold  PSilver  PBronze  Total
58  SGP  Singapore      0        0        0      0

In [64]:
tokyo2020_predicted[tokyo2020_predicted['country'] =='Japan']

   NOC country  PGold  PSilver  PBronze  Total
8  JPN   Japan     12        9        9     30

In [63]:
olympics_all[olympics_all['country']=='Japan']

,Year,NOC,country,Population,Gdp,GDP_Per_Capita,Home_Field,Athletes,Athletes_w,Sports,Sports_w,Events,Events_w,Gold,Silver,Bronze,Medals
31,1992,JPN,Japan,124229000.0,3.900000e+12,31393.64,0,256,44,24,8,166,22,3,8,11,22
99,1996,JPN,Japan,125757000.0,4.830000e+12,38407.40,0,306,42,27,7,168,14,3,6,5,14
180,2000,JPN,Japan,126843000.0,4.890000e+12,38551.60,0,266,41,28,7,156,18,5,8,5,18
256,2004,JPN,Japan,127761000.0,4.820000e+12,37726.69,0,305,84,31,11,169,37,16,9,12,37
333,2008,JPN,Japan,128063000.0,5.040000e+12,39355.63,0,332,48,31,9,176,25,9,7,9,25
419,2012,JPN,Japan,127629000.0,6.200000e+12,48578.30,0,291,76,29,13,178,38,7,14,17,38
503,2016,JPN,Japan,126994511.0,4.940000e+12,38899.32,0,335,57,32,11,186,40,12,8,21,41

In [ ]:
#Test set - Actual vs Prediction

plt.figure(figsize =(20,4))
plt.subplot(1,3,1)
plt.scatter(y_test['Gold'],y_pred_Gold)
plt.title("Actual Vs Prediction-Gold")
plt.xlabel("Actual")
plt.ylabel("Predicted")


plt.subplot(1,3,2)
plt.scatter(y_test['Silver'],y_pred_Silver)
plt.title("Actual Vs Prediction-Silver")
plt.xlabel("Actual")
plt.ylabel("Predicted")


plt.subplot(1,3,3)
plt.scatter(y_test['Bronze'],y_pred_Bronze)
plt.title("Actual Vs Prediction-Bronze")
plt.xlabel("Actual")
plt.ylabel("Predicted")
plt.show

In [ ]:
from yellowbrick.regressor import PredictionError


visualizer = PredictionError(rf_gold, title = 'Gold')
visualizer.fit(X_train,y_train['Gold'])
visualizer.score(X_test,y_test['Gold'])
visualizer.poof()

visualizer = PredictionError(rf_silver, title = 'Silver')
visualizer.fit(X_train,y_train['Silver'])
visualizer.score(X_test,y_test['Silver'])
visualizer.poof()

visualizer = PredictionError(rf_bronze, title = 'Bronze')
visualizer.fit(X_train,y_train['Bronze'])
visualizer.score(X_test,y_test['Bronze'])
visualizer.poof()

In [42]:
#feature importance


feature_importance = np.array(rf_gold.feature_importances_)
feature_names = np.array(X_train.columns)
feat_imp = pd.DataFrame({'feature_names':feature_names,'feature_importance':feature_importance})
feat_imp_sorted = feat_imp.sort_values('feature_importance', ascending=False)
print(feat_imp_sorted)

  feature_names  feature_importance
8      Events_w            0.915771
0    Population            0.023742
1           Gdp            0.021947
4    Athletes_w            0.011063
7        Events            0.006812
3      Athletes            0.006066
6      Sports_w            0.006026
5        Sports            0.005906
2    Home_Field            0.002667

In [43]:
feature_importance = np.array(rf_silver.feature_importances_)
feature_names = np.array(X_train.columns)
feat_imp = pd.DataFrame({'feature_names':feature_names,'feature_importance':feature_importance})
feat_imp_sorted = feat_imp.sort_values('feature_importance', ascending=False)
print(feat_imp_sorted)

  feature_names  feature_importance
8      Events_w            0.913840
4    Athletes_w            0.024170
0    Population            0.015071
3      Athletes            0.011131
1           Gdp            0.010704
7        Events            0.010423
6      Sports_w            0.007769
5        Sports            0.006708
2    Home_Field            0.000184

In [44]:
feature_importance = np.array(rf_bronze.feature_importances_)
feature_names = np.array(X_train.columns)
feat_imp = pd.DataFrame({'feature_names':feature_names,'feature_importance':feature_importance})
feat_imp_sorted = feat_imp.sort_values('feature_importance', ascending=False)
print(feat_imp_sorted)

  feature_names  feature_importance
8      Events_w            0.875616
7        Events            0.037319
4    Athletes_w            0.031651
6      Sports_w            0.019732
0    Population            0.010261
1           Gdp            0.009928
3      Athletes            0.009675
5        Sports            0.005150
2    Home_Field            0.000667